### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by ericawright** [mozilla/something-awesome#27]
- Add a linter so that we all follow the same coding conventions
https://github.com/eslint/eslint
https://github.com/stylelint/stylelint

- Protect master branch, and hook up Travis or Circle CI to check that it passes for PRs

**Comment by pdehaan** [comment]
For ESLint, probably something like this (at a minimum):

```yaml
env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended

rules:
  eqeqeq: error
  no-console: warn
  no-var: error
  one-var: [error, never]
  prefer-const: error
  quotes: [error, single]
```

**Comment by pdehaan** [comment]
I haven't used **stylelint** a bunch, but this seems to work as a minimal config (plus, latest version of **prettier** also formats CSS files):

```diff
  "devDependencies": {
    ...
    "prettier": "1.4.4",
+   "stylelint": "7.10.1",
+   "stylelint-config-standard": "16.0.0",
    ...
  },
  "scripts": {
+   "format:css": "prettier --write 'public/*.css'",
+   "lint:css": "stylelint 'public/*.css' --fix",
    ...
  }
```

And then a .stylelintrc config file of:

```yaml
extends:
  - stylelint-config-standard

rules:
  selector-list-comma-newline-after: null
```
